use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, BTreeSet};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let asm_dir = Path::new(&manifest_dir).join("asm");

    // Assemble all .asm files in the asm/ directory using NASM
    let asm_files = [
        "multiboot_header.asm",
        "boot.asm",
        "syscall_entry.asm",
        "trap_entry.asm",
        "switch.asm",
        "user_agents.asm",
        "ap_trampoline.asm",
    ];

    for asm_file in &asm_files {
        let src = asm_dir.join(asm_file);
        let obj_name = asm_file.replace(".asm", ".o");
        let obj = Path::new(&out_dir).join(&obj_name);

        let status = Command::new("nasm")
            .args(["-f", "elf64", "-o"])
            .arg(&obj)
            .arg(&src)
            .status()
            .expect("Failed to run nasm. Is nasm installed?");

        if !status.success() {
            panic!("nasm failed to assemble {}", asm_file);
        }

        println!("cargo:rustc-link-arg={}", obj.display());
    }

    let linker_script = Path::new(&manifest_dir).join("linker.ld");
    println!("cargo:rustc-link-arg=-T{}", linker_script.display());

    println!("cargo:rerun-if-changed=asm/");
    println!("cargo:rerun-if-changed=linker.ld");
    for asm_file in &asm_files {
        println!("cargo:rerun-if-changed=asm/{}", asm_file);
    }

    emit_base_image_manifest(&manifest_dir, &out_dir);
}

fn emit_base_image_manifest(manifest_dir: &str, out_dir: &str) {
    let manifest_dir_path = Path::new(manifest_dir);
    let generated_path = Path::new(out_dir).join("base_image_manifest.rs");
    println!("cargo:rerun-if-env-changed=TOS_RUNTIME_MANIFEST");

    let mut manifest_paths = vec![manifest_dir_path.join("base_image.manifest")];
    let runtime_manifest = match env::var("TOS_RUNTIME_MANIFEST") {
        Ok(path) if !path.trim().is_empty() => {
            let resolved = resolve_host_path(manifest_dir_path, path.trim());
            if !resolved.exists() {
                panic!(
                    "TOS_RUNTIME_MANIFEST points to missing file '{}'",
                    resolved.display()
                );
            }
            resolved
        }
        _ => manifest_dir_path.join("base_image.runtime.manifest"),
    };
    manifest_paths.push(runtime_manifest);

    let mut entries: BTreeMap<String, PathBuf> = BTreeMap::new();

    for manifest_path in &manifest_paths {
        println!("cargo:rerun-if-changed={}", manifest_path.display());
        if manifest_path.exists() {
            load_manifest_entries(manifest_dir_path, manifest_path, &mut entries);
        }
    }

    let mut generated = String::from("// @generated by build.rs\n");
    generated.push_str("pub static EMBEDDED_BASE_IMAGE_FILES: &[EmbeddedBaseImageFile] = &[\n");
    for (tos_path, source_path) in entries {
        let key = base_image_key(&tos_path);
        generated.push_str("    EmbeddedBaseImageFile {\n");
        generated.push_str(&format!("        path: {:?},\n", tos_path));
        generated.push_str(&format!("        key: 0x{:016x},\n", key));
        generated.push_str(&format!(
            "        data: include_bytes!({:?}) as &[u8],\n",
            source_path.display().to_string()
        ));
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    fs::write(&generated_path, generated).expect("failed to write base image manifest source");
}

fn load_manifest_entries(
    root: &Path,
    manifest_path: &Path,
    entries: &mut BTreeMap<String, PathBuf>,
) {
    let contents = fs::read_to_string(manifest_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {}", manifest_path.display(), e));

    for (line_no, raw_line) in contents.lines().enumerate() {
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some(rest) = line.strip_prefix("@tree ") {
            let (tos_prefix, host_root) = split_mapping(rest, manifest_path, line_no);
            let host_root = resolve_host_path(root, &host_root);
            println!("cargo:rerun-if-changed={}", host_root.display());
            collect_tree_entries(&tos_prefix, &host_root, entries);
            continue;
        }

        let (tos_path, host_path) = split_mapping(line, manifest_path, line_no);
        let host_path = resolve_host_path(root, &host_path);
        println!("cargo:rerun-if-changed={}", host_path.display());
        entries.insert(tos_path, host_path);
    }
}

fn split_mapping(line: &str, manifest_path: &Path, line_no: usize) -> (String, String) {
    let (lhs, rhs) = line.split_once('=').unwrap_or_else(|| {
        panic!(
            "Invalid {} line {}: expected '/tos/path = host/path'",
            manifest_path.display(),
            line_no + 1
        )
    });

    let tos_path = lhs.trim().to_string();
    let host_path = rhs.trim().to_string();

    if !tos_path.starts_with('/') {
        panic!(
            "Invalid TOS path in {} line {}: '{}' must be absolute",
            manifest_path.display(),
            line_no + 1,
            tos_path
        );
    }

    (tos_path, host_path)
}

fn resolve_host_path(root: &Path, host_path: &str) -> PathBuf {
    let path = Path::new(host_path);
    let resolved = if path.is_absolute() {
        path.to_path_buf()
    } else {
        root.join(path)
    };

    fs::canonicalize(&resolved).unwrap_or_else(|e| {
        panic!(
            "Failed to resolve host path '{}': {}",
            resolved.display(),
            e
        )
    })
}

fn collect_tree_entries(
    tos_prefix: &str,
    host_root: &Path,
    entries: &mut BTreeMap<String, PathBuf>,
) {
    if !host_root.is_dir() {
        panic!("tree source '{}' is not a directory", host_root.display());
    }

    let tos_prefix = tos_prefix.trim_end_matches('/');
    let mut stack = vec![host_root.to_path_buf()];
    let mut visited_dirs = BTreeSet::new();

    while let Some(dir) = stack.pop() {
        let canonical_dir = fs::canonicalize(&dir)
            .unwrap_or_else(|e| panic!("canonicalize {} failed: {}", dir.display(), e));
        if !visited_dirs.insert(canonical_dir.clone()) {
            continue;
        }

        for entry in fs::read_dir(&dir)
            .unwrap_or_else(|e| panic!("read_dir {} failed: {}", dir.display(), e))
        {
            let entry = entry
                .unwrap_or_else(|e| panic!("directory entry error in {}: {}", dir.display(), e));
            let path = entry.path();
            let metadata = match fs::symlink_metadata(&path) {
                Ok(meta) if meta.file_type().is_symlink() => match fs::metadata(&path) {
                    Ok(target_meta) => target_meta,
                    Err(err) => {
                        eprintln!(
                            "cargo:warning=skipping dangling symlink in base-image tree: {} ({})",
                            path.display(),
                            err
                        );
                        continue;
                    }
                },
                Ok(meta) => meta,
                Err(e) => panic!("metadata failed for {}: {}", path.display(), e),
            };

            if metadata.is_dir() {
                stack.push(path);
                continue;
            }

            if !metadata.is_file() {
                continue;
            }

            let rel = path.strip_prefix(host_root).unwrap();
            let rel = rel
                .to_str()
                .unwrap_or_else(|| panic!("non-utf8 path not supported: {}", path.display()))
                .replace('\\', "/");
            let tos_path = if tos_prefix.is_empty() {
                format!("/{}", rel)
            } else {
                format!("{}/{}", tos_prefix, rel)
            };

            println!("cargo:rerun-if-changed={}", path.display());
            entries.insert(tos_path, fs::canonicalize(&path).unwrap());
        }
    }
}

fn base_image_key(tos_path: &str) -> u64 {
    if tos_path == "/etc/ld.so.cache" {
        return sha256_key(b"base:ld.so.cache");
    }
    if let Some(relative) = tos_path.strip_prefix("/etc/") {
        return sha256_key_prefixed(b"base:etc/", relative.as_bytes());
    }
    if let Some(relative) = tos_path.strip_prefix("/lib/") {
        return sha256_key_prefixed(b"base:lib/", relative.as_bytes());
    }
    if let Some(relative) = tos_path.strip_prefix("/lib64/") {
        return sha256_key_prefixed(b"base:lib/", relative.as_bytes());
    }
    if let Some(relative) = tos_path.strip_prefix("/usr/lib/") {
        return sha256_key_prefixed(b"base:lib/", relative.as_bytes());
    }
    if let Some(relative) = tos_path.strip_prefix("/usr/bin/") {
        return sha256_key_prefixed(b"base:usrbin/", relative.as_bytes());
    }
    if let Some(relative) = tos_path.strip_prefix("/jdk/") {
        return sha256_key_prefixed(b"base:jdk/", relative.as_bytes());
    }

    panic!(
        "Unsupported base-image path '{}' in manifest; add VFS routing first",
        tos_path
    );
}

fn sha256_key(data: &[u8]) -> u64 {
    let hash = Sha256::digest(data);
    u64::from_le_bytes([
        hash[0], hash[1], hash[2], hash[3], hash[4], hash[5], hash[6], hash[7],
    ])
}

fn sha256_key_prefixed(prefix: &[u8], suffix: &[u8]) -> u64 {
    let mut hasher = Sha256::new();
    hasher.update(prefix);
    hasher.update(suffix);
    let hash = hasher.finalize();
    u64::from_le_bytes([
        hash[0], hash[1], hash[2], hash[3], hash[4], hash[5], hash[6], hash[7],
    ])
}
