//! Unified error type for the ATOS WASM engine.

// ─── Error type ──────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum WasmError {
    InvalidMagic,
    UnsupportedVersion,
    InvalidSection,
    InvalidOpcode(u8),
    StackOverflow,
    StackUnderflow,
    TypeMismatch,
    OutOfBounds,
    DivisionByZero,
    UnreachableExecuted,
    ImportNotFound(u32),
    FunctionNotFound(u32),
    TooManyFunctions,
    TooManyImports,
    CodeTooLarge,
    InvalidLEB128,
    OutOfFuel,
    MemoryOutOfBounds,
    CallStackOverflow,
    InvalidBlockType,
    BranchDepthExceeded,
    UnexpectedEnd,
    IntegerOverflow,
    FloatsDisabled,
    UndefinedElement,
    UninitializedElement(u32),
    IndirectCallTypeMismatch,
    ImmutableGlobal,
    GlobalIndexOutOfBounds,
    UnsupportedProposal,
    TableIndexOutOfBounds,
    DuplicateExport,
    InvalidConversionToInteger,
    MalformedUtf8,
    ZeroByteExpected,
    ConstExprRequired,
    UndeclaredFuncRef,
    NullFunctionReference,
    NullReference,
    NullI31Reference,
    NullStructReference,
    NullArrayReference,
    ArrayOutOfBounds,
    UninitializedLocal,
    UnalignedAtomic,
    UncaughtException,
    CastFailure,
    MultipleTables,
}
