//! Embeds the vendored x86 SLEIGH language files into the wasm module so the
//! engine can compile the specification without a filesystem.

use std::{fmt::Write as _, path::PathBuf};

fn main() {
    let languages =
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../third_party/ghidra-x86/languages");
    println!("cargo:rerun-if-changed={}", languages.display());

    let mut entries = Vec::new();
    let dir = std::fs::read_dir(&languages)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", languages.display()));
    for entry in dir {
        let entry = entry.expect("directory entry");
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        // The language set is UTF-8 text; skip anything that is not (there
        // is nothing includable that would be).
        if std::fs::read_to_string(&path).is_err() {
            continue;
        }
        let name = entry.file_name().into_string().expect("UTF-8 file name");
        entries.push((name, path));
    }
    entries.sort();

    let mut code = String::from(
        "/// SLEIGH language files (file name -> content), generated by build.rs.\n\
         pub static SPEC_FILES: &[(&str, &str)] = &[\n",
    );
    for (name, path) in &entries {
        writeln!(code, "    ({name:?}, include_str!({:?})),", path.display()).expect("write");
    }
    code.push_str("];\n");

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("spec_files.rs");
    std::fs::write(&out, code).expect("write spec_files.rs");
}
