[build]
target = "x86_64-unknown-atos.json"

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
json-target-spec = true

[target.'cfg(target_os = "atos")']
runner = "qemu-system-x86_64 -serial stdio -display none -no-reboot -no-shutdown -kernel"
rustflags = []
