#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: tools/prepare_jtreg_assets.sh [options]

Prepare host-side assets for the first guest-side OpenJDK 11 jtreg smoke on TOS.

This script downloads:
  - jtreg 7.3.1+1 (recommended for JDK 11+)
  - a sparse OpenJDK jdk11u checkout containing:
      test/jdk
      test/lib
      test/jtreg-ext

It then writes a ready-to-use runtime manifest:
  base_image.runtime.jtreg.manifest

Options:
  --assets-dir PATH        Asset cache root (default: /tmp/tos-jtreg-assets)
  --manifest PATH          Output manifest path
                           (default: base_image.runtime.jtreg.manifest)
  --jdk-home PATH          JDK 11 home to embed
                           (default: /usr/lib/jvm/java-11-openjdk-amd64)
  --java-conf PATH         Java config dir to embed
                           (default: /etc/java-11-openjdk)
  --keep-clone             Keep existing jdk11u checkout if present
  -h, --help               Show this help
EOF
}

assets_dir="/tmp/tos-jtreg-assets"
manifest_path="base_image.runtime.jtreg.manifest"
jdk_home="/usr/lib/jvm/java-11-openjdk-amd64"
java_conf="/etc/java-11-openjdk"
keep_clone=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --assets-dir)
      assets_dir="$2"
      shift 2
      ;;
    --manifest)
      manifest_path="$2"
      shift 2
      ;;
    --jdk-home)
      jdk_home="$2"
      shift 2
      ;;
    --java-conf)
      java_conf="$2"
      shift 2
      ;;
    --keep-clone)
      keep_clone=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if [[ ! -x "$jdk_home/bin/java" ]]; then
  echo "JDK home not found: $jdk_home" >&2
  exit 1
fi

if [[ ! -d "$java_conf" ]]; then
  echo "Java config dir not found: $java_conf" >&2
  exit 1
fi

jtreg_dir="$assets_dir/jtreg-7.3.1+1"
jdk_src_dir="$assets_dir/jdk11u"

mkdir -p "$assets_dir"

if [[ ! -x "$jtreg_dir/jtreg/bin/jtreg" ]]; then
  rm -rf "$jtreg_dir"
  mkdir -p "$jtreg_dir"
  (
    cd "$jtreg_dir"
    curl -fsSL -o jtreg-7.3.1+1.zip \
      https://builds.shipilev.net/jtreg/jtreg-7.3.1%2B1.zip
    unzip -q jtreg-7.3.1+1.zip
  )
fi

if [[ "$keep_clone" -eq 0 ]]; then
  rm -rf "$jdk_src_dir"
fi

if [[ ! -d "$jdk_src_dir/.git" ]]; then
  git clone --depth 1 --filter=blob:none --sparse https://github.com/openjdk/jdk11u.git "$jdk_src_dir"
fi

(
  cd "$jdk_src_dir"
  git sparse-checkout set test/jdk test/lib test/jtreg-ext
)

jtreg_home="$(cd "$jtreg_dir/jtreg" && pwd)"
jdk_src_root="$(cd "$jdk_src_dir" && pwd)"
jdk_home_abs="$(cd "$jdk_home" && pwd)"
java_conf_abs="$(cd "$java_conf" && pwd)"

cat >"$manifest_path" <<EOF
# Auto-generated by tools/prepare_jtreg_assets.sh
# Guest-side OpenJDK 11 jtreg smoke profile for TOS.

@tree /usr/lib/jvm/java-11-openjdk-amd64 = $jdk_home_abs
@tree /etc/java-11-openjdk = $java_conf_abs

/lib64/ld-linux-x86-64.so.2 = /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2
/lib/x86_64-linux-gnu/libc.so.6 = /usr/lib/x86_64-linux-gnu/libc.so.6
/lib/x86_64-linux-gnu/libm.so.6 = /usr/lib/x86_64-linux-gnu/libm.so.6
/lib/x86_64-linux-gnu/libz.so.1 = /usr/lib/x86_64-linux-gnu/libz.so.1.2.11
/lib/x86_64-linux-gnu/libstdc++.so.6 = /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30
/lib/x86_64-linux-gnu/libgcc_s.so.1 = /usr/lib/x86_64-linux-gnu/libgcc_s.so.1

@tree /jdk/jtreg = $jtreg_home
@tree /jdk/test/jdk = $jdk_src_root/test/jdk
@tree /jdk/test/lib = $jdk_src_root/test/lib
@tree /jdk/test/jtreg-ext = $jdk_src_root/test/jtreg-ext
EOF

echo "[jtreg-prepare] jtreg home: $jtreg_home"
echo "[jtreg-prepare] OpenJDK test root: $jdk_src_root/test"
echo "[jtreg-prepare] manifest written: $manifest_path"
